// <auto-generated />
using AdedonhaMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdedonhaMVC.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20231121124958_APICarros")]
    partial class APICarros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdedonhaMVC.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descricao");

                    b.Property<int>("TotalPalavras")
                        .HasColumnType("int")
                        .HasColumnName("TotalPalavras");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("AdedonhaMVC.Models.Palavra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Informacao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Informacao");

                    b.HasKey("Id");

                    b.ToTable("Palavra");
                });

            modelBuilder.Entity("CategoriaPalavra", b =>
                {
                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("PalavraId")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId", "PalavraId");

                    b.HasIndex("PalavraId");

                    b.ToTable("CategoriaPalavra", (string)null);
                });

            modelBuilder.Entity("CategoriaPalavra", b =>
                {
                    b.HasOne("AdedonhaMVC.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CategoriaPalavra_Categoria_CategoriaId");

                    b.HasOne("AdedonhaMVC.Models.Palavra", null)
                        .WithMany()
                        .HasForeignKey("PalavraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CategoriaPalavra_Palavra_PalavraId");
                });
#pragma warning restore 612, 618
        }
    }
}
